Repository alarm-redist/fifty-states, pull requests merged in 2022-06, with the labels that each got.

#81 Re-run 2020 Oregon Congressional Districts
  R/template/03_sim.R
  analyses/OR_cd_2020/01_prep_OR_cd_2020.R
  analyses/OR_cd_2020/03_sim_OR_cd_2020.R
  analyses/OR_cd_2020/doc_OR_cd_2020.md
  fifty-states.Rproj
Labels: rerun, awaiting review

#92 Re-run 2020 Iowa Congressional Districts
  analyses/IA_cd_2020/03_sim_IA_cd_2020.R
  analyses/IA_cd_2020/doc_IA_cd_2020.md
Labels: rerun, awaiting review

#93 Re-run 2020 Michigan Congressional Districts
  R/template/dataverse_addendum.md
  analyses/MI_cd_2020/02_setup_MI_cd_2020.R
  analyses/MI_cd_2020/03_sim_MI_cd_2020.R
  analyses/MI_cd_2020/doc_MI_cd_2020.md
Labels: rerun, awaiting review

#99 Re-run 2020 Washington Congressional Districts
  analyses/WA_cd_2020/03_sim_WA_cd_2020.R
  analyses/WA_cd_2020/doc_WA_cd_2020.md
Labels: rerun, awaiting review

#103 Re-run 2020 Mississippi Congressional Districts
  DESCRIPTION
  analyses/MS_cd_2020/01_prep_MS_cd_2020.R
  analyses/MS_cd_2020/03_sim_MS_cd_2020.R
  analyses/MS_cd_2020/doc_MS_cd_2020.md
  fifty-states.Rproj
Labels: rerun, awaiting review

#95 Re-run 2020 Montana Congressional Districts
  analyses/MT_cd_2020/03_sim_MT_cd_2020.R
  analyses/MT_cd_2020/doc_MT_cd_2020.md
Labels: rerun, awaiting review

#96 Re-run 2020 Nebraska Congressional Districts
  analyses/NE_cd_2020/02_setup_NE_cd_2020.R
  analyses/NE_cd_2020/03_sim_NE_cd_2020.R
  analyses/NE_cd_2020/doc_NE_cd_2020.md
Labels: rerun, awaiting review

#104 Re-run 2020 West Virginia Congressional Districts
  analyses/WV_cd_2020/01_prep_WV_cd_2020.R
  analyses/WV_cd_2020/03_sim_WV_cd_2020.R
  analyses/WV_cd_2020/doc_WV_cd_2020.md
Labels: rerun, awaiting review

#105 Re-run 2020 Idaho Congressional Districts
  analyses/ID_cd_2020/01_prep_ID_cd_2020.R
  analyses/ID_cd_2020/03_sim_ID_cd_2020.R
  analyses/ID_cd_2020/doc_ID_cd_2020.md
Labels: rerun, awaiting review

#102 Re-run 2020 Kansas Congressional Districts
  analyses/KS_cd_2020/02_setup_KS_cd_2020.R
  analyses/KS_cd_2020/03_sim_KS_cd_2020.R
  analyses/KS_cd_2020/doc_KS_cd_2020.md
Labels: rerun, awaiting review

#101 Re-run 2020 Rhode Island Congressional Districts
  analyses/RI_cd_2020/01_prep_RI_cd_2020.R
  analyses/RI_cd_2020/03_sim_RI_cd_2020.R
  analyses/RI_cd_2020/doc_RI_cd_2020.md
Labels: rerun, awaiting review

#53 2020 Missouri Congressional Districts
  analyses/MO_cd_2020/01_prep_MO_cd_2020.R
  analyses/MO_cd_2020/02_setup_MO_cd_2020.R
  analyses/MO_cd_2020/03_sim_MO_cd_2020.R
  analyses/MO_cd_2020/doc_MO_cd_2020.md
Labels: awaiting review

#106 Re-run 2020 Maine Congressional Districts
  analyses/ME_cd_2020/01_prep_ME_cd_2020.R
  analyses/ME_cd_2020/03_sim_ME_cd_2020.R
  analyses/ME_cd_2020/doc_ME_cd_2020.md
Labels: rerun, awaiting review

#98 Re-run 2020 Pennsylvania Congressional Districts
  analyses/PA_cd_2020/03_sim_PA_cd_2020.R
  analyses/PA_cd_2020/doc_PA_cd_2020.md
Labels: rerun, question, awaiting review

#107 Re-run 2020 Nevada Congressional Districts
  analyses/NV_cd_2020/01_prep_NV_cd_2020.R
  analyses/NV_cd_2020/03_sim_NV_cd_2020.R
  analyses/NV_cd_2020/doc_NV_cd_2020.md
Labels: rerun, awaiting review

#97 Re-run 2020 Ohio Congressional Districts
  analyses/OH_cd_2020/01_prep_OH_cd_2020.R
  analyses/OH_cd_2020/03_sim_OH_cd_2020.R
  analyses/OH_cd_2020/doc_OH_cd_2020.md
Labels: rerun, awaiting review

#94 2020 Georgia Congressional Districts
  analyses/GA_cd_2020/03_sim_GA_cd_2020.R
  analyses/GA_cd_2020/doc_GA_cd_2020.md
Labels: rerun

#108 Re-run 2020 Oklahoma Congressional Districts
  analyses/OK_cd_2020/01_prep_OK_cd_2020.R
  analyses/OK_cd_2020/03_sim_OK_cd_2020.R
  analyses/OK_cd_2020/doc_OK_cd_2020.md
Labels: rerun, awaiting review

#115 Re-run 2020 Arkansas Congressional Districts
  analyses/AR_cd_2020/03_sim_AR_cd_2020.R
  analyses/AR_cd_2020/doc_AR_cd_2020.md
Labels: rerun

#117 Re-run 2020 Minnesota Congressional Districts
  analyses/MN_cd_2020/02_setup_MN_cd_2020.R
  analyses/MN_cd_2020/03_sim_MN_cd_2020.R
  analyses/MN_cd_2020/doc_MN_cd_2020.md
Labels: rerun, awaiting review

#119 Re-run 2020 New Mexico Congressional Districts
  analyses/NM_cd_2020/02_setup_NM_cd_2020.R
  analyses/NM_cd_2020/03_sim_NM_cd_2020.R
  analyses/NM_cd_2020/doc_NM_cd_2020.md
Labels: rerun, awaiting review

#114 Re-run 2020 Wisconsin Congressional Districts
  analyses/WI_cd_2020/02_setup_WI_cd_2020.R
  analyses/WI_cd_2020/03_sim_WI_cd_2020.R
  analyses/WI_cd_2020/doc_WI_cd_2020.md
Labels: revise documentation, rerun

#111 Re-run 2020 Hawaii Congressional Districts
  analyses/HI_cd_2020/01_prep_HI_cd_2020.R
  analyses/HI_cd_2020/03_sim_HI_cd_2020.R
  analyses/HI_cd_2020/doc_HI_cd_2020.md
Labels: rerun

#85 2020 South Carolina Congressional Districts
  analyses/SC_cd_2020/01_prep_SC_cd_2020.R
  analyses/SC_cd_2020/02_setup_SC_cd_2020.R
  analyses/SC_cd_2020/03_sim_SC_cd_2020.R
  analyses/SC_cd_2020/doc_SC_cd_2020.md
Labels: awaiting review

#123 Re-run 2020 New York Congressional Districts
  analyses/NY_cd_2020/01_prep_NY_cd_2020.R
  analyses/NY_cd_2020/03_sim_NY_cd_2020.R
  analyses/NY_cd_2020/doc_NY_cd_2020.md
Labels: rerun

#118 Re-run 2020 Louisiana Congressional Districts
  analyses/LA_cd_2020/03_sim_LA_cd_2020.R
  analyses/LA_cd_2020/doc_LA_cd_2020.md
Labels: rerun, awaiting review

#124 Re-run 2020 Texas Congressional Districts
  analyses/TX_cd_2020/03_sim_TX_cd_2020.R
  analyses/TX_cd_2020/04_diagnostics_TX_cd_2020.R
  analyses/TX_cd_2020/doc_TX_cd_2020.md
Labels: rerun, awaiting review

#121 Re-run 2020 Virginia Congressional Districts
  analyses/VA_cd_2020/01_prep_VA_cd_2020.R
  analyses/VA_cd_2020/03_sim_VA_cd_2020.R
  analyses/VA_cd_2020/doc_VA_cd_2020.md
Labels: rerun, awaiting review

#126 Rerun 2020 Illinois Congressional Districts
  analyses/IL_cd_2020/01_prep_IL_cd_2020.R
  analyses/IL_cd_2020/02_setup_IL_cd_2020.R
  analyses/IL_cd_2020/03_sim_IL_cd_2020.R
  analyses/IL_cd_2020/doc_IL_cd_2020.md
Labels: rerun, awaiting review
