Repository alarm-redist/fifty-states, pull requests merged in 2023-01, with the labels that each got.

#148 2010 New Mexico Congressional Districts
  analyses/NM_cd_2010/01_prep_NM_cd_2010.R
  analyses/NM_cd_2010/02_setup_NM_cd_2010.R
  analyses/NM_cd_2010/03_sim_NM_cd_2010.R
  analyses/NM_cd_2010/doc_NM_cd_2010.md
Labels: awaiting review

#144 2010 Pennsylvania Congressional Districts
  analyses/PA_cd_2010/01_prep_PA_cd_2010.R
  analyses/PA_cd_2010/02_setup_PA_cd_2010.R
  analyses/PA_cd_2010/03_sim_PA_cd_2010.R
  analyses/PA_cd_2010/doc_PA_cd_2010.md
Labels: revise code

#158 2010 Virginia Congressional Districts
  analyses/VA_cd_2010/01_prep_VA_cd_2010.R
  analyses/VA_cd_2010/02_setup_VA_cd_2010.R
  analyses/VA_cd_2010/03_sim_VA_cd_2010.R
  analyses/VA_cd_2010/doc_VA_cd_2010.md
Labels: revise documentation

#140 2010 Massachusetts Congressional Districts
  analyses/MA_cd_2010/01_prep_MA_cd_2010.R
  analyses/MA_cd_2010/02_setup_MA_cd_2010.R
  analyses/MA_cd_2010/03_sim_MA_cd_2010.R
  analyses/MA_cd_2010/doc_MA_cd_2010.md
Labels: revise documentation

#153 2010 Iowa Congressional Districts
  analyses/IA_cd_2010/01_prep_IA_cd_2010.R
  analyses/IA_cd_2010/02_setup_IA_cd_2010.R
  analyses/IA_cd_2010/03_sim_IA_cd_2010.R
  analyses/IA_cd_2010/doc_IA_cd_2010.md
Labels: question
