Repository alarm-redist/fifty-states, pull requests merged in 2023-02, with the labels that each got.

#162 2010 Massachusetts Congressional Districts
  analyses/MA_cd_2010/01_prep_MA_cd_2010.R
  analyses/MA_cd_2010/03_sim_MA_cd_2010.R
  analyses/MA_cd_2010/doc_MA_cd_2010.md
Labels: revise documentation, revise code

#156 2010 Tennessee Congressional Districts
  analyses/TN_cd_2010/01_prep_TN_cd_2010.R
  analyses/TN_cd_2010/02_setup_TN_cd_2010.R
  analyses/TN_cd_2010/03_sim_TN_cd_2010.R
  analyses/TN_cd_2010/doc_TN_cd_2010.md
Labels: awaiting review

#152 2010 Arizona Congressional Districts
  analyses/AZ_cd_2010/01_prep_AZ_cd_2010.R
  analyses/AZ_cd_2010/02_setup_AZ_cd_2010.R
  analyses/AZ_cd_2010/03_sim_AZ_cd_2010.R
  analyses/AZ_cd_2010/doc_AZ_cd_2010.md
Labels: awaiting review

#169 2010 Kansas Congressional Districts
  analyses/KS_cd_2010/01_prep_KS_cd_2010.R
  analyses/KS_cd_2010/02_setup_KS_cd_2010.R
  analyses/KS_cd_2010/03_sim_KS_cd_2010.R
  analyses/KS_cd_2010/doc_KS_cd_2010.md
Labels: awaiting review

#149 2010 Alabama Congressional Districts
  analyses/AL_cd_2010/01_prep_AL_cd_2010.R
  analyses/AL_cd_2010/02_setup_AL_cd_2010.R
  analyses/AL_cd_2010/03_sim_AL_cd_2010.R
  analyses/AL_cd_2010/doc_AL_cd_2010.md
Labels: awaiting review

#139 2010 Louisiana Congressional Districts
  analyses/LA_cd_2010/01_prep_LA_cd_2010.R
  analyses/LA_cd_2010/02_setup_LA_cd_2010.R
  analyses/LA_cd_2010/03_sim_LA_cd_2010.R
  analyses/LA_cd_2010/doc_LA_cd_2010.md
Labels: awaiting review

#154 2010 Hawaii Congressional Districts
  analyses/HI_cd_2010/01_prep_HI_cd_2010.R
  analyses/HI_cd_2010/02_setup_HI_cd_2010.R
  analyses/HI_cd_2010/03_sim_HI_cd_2010.R
  analyses/HI_cd_2010/doc_HI_cd_2010.md
Labels: awaiting review

#145 2010 Wisconsin Congressional Districts
  analyses/WI_cd_2010/01_prep_WI_cd_2010.R
  analyses/WI_cd_2010/02_setup_WI_cd_2010.R
  analyses/WI_cd_2010/03_sim_WI_cd_2010.R
  analyses/WI_cd_2010/doc_WI_cd_2010.md
Labels: question

#170 2010 Texas Congressional Districts
  analyses/TX_cd_2010/01_prep_TX_cd_2010.R
  analyses/TX_cd_2010/02_setup_TX_cd_2010.R
  analyses/TX_cd_2010/03_sim_TX_cd_2010.R
  analyses/TX_cd_2010/04_diagnostics_TX_cd_2010.R
  analyses/TX_cd_2010/doc_TX_cd_2010.md
Labels: awaiting review

#172 2010 Rhode Island Congressional Districts
  analyses/RI_cd_2010/01_prep_RI_cd_2010.R
  analyses/RI_cd_2010/02_setup_RI_cd_2010.R
  analyses/RI_cd_2010/03_sim_RI_cd_2010.R
  analyses/RI_cd_2010/doc_RI_cd_2010.md
Labels: revise documentation, revise code
